# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: David Cannan's Portfolio

tagline: Software Developer, Embedded Engineer, and Cybersecurity Enthusiast

description: >- 
  A personal portfolio showcasing the work of David Cannan, a self-taught software developer, embedded engineer, and cybersecurity enthusiast from Douglasville, Georgia.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: ""

github:
  username: davidcannan

twitter:
  username: davidcannan

social:
  name: David Cannan
  email: david.cannan@example.com
  links:
    - https://twitter.com/davidcannan
    - https://github.com/davidcannan

google_site_verification: 

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: 
  pv:
    proxy_endpoint: 
    cache_path: 

theme_mode: 

img_cdn: "https://chirpy-img.netlify.app"

avatar: "/commons/avatar.jpg"

toc: true

comments:
  active: 
  disqus:
    shortname: 
  utterances:
    repo: 
    issue_term: 
  giscus:
    repo: 
    repo_id:
    category:
    category_id:
    mapping: 
    input_position: 
    lang: 
    reactions_enabled: 

assets:
  self_host:
    enabled: 
    env: 

pwa:
  enabled: true 

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude
